### PR TITLE
Sync with the upstream v6.8.0

### PR DESCRIPTION
**Pull request by hankwallace**
**Overview**

- This updates our fork with v6.8.0 in the upstream repo. The plan is to upgrade further after this is merged.
- After resolving conflicts, I compared all changes with the changes in the upstream from v6.6.0 to v6.8.0. Link is [here](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/compare/v6.6.0...image/v6.8.0)
- Also added our company logo to the web ui banner.

**How it was tested**

- Built and ran unit tests
- Configured docker-compose to use MySQL, started it, and ran all of our integration tests against it.
- Configured docker-compose to use PostgreSQL, started it, and ran all of our integration tests against it.

**Checklist**

- [x] The title contains a short meaningful summary
- [x]  I have added a link to this PR in the Jira issue
- [x]  I have described how this was tested
- [ ]  I have included screen shots for changes that affect the user interface
- [ ]  I have updated unit tests
- [x]  I have run unit tests locally
- [ ]  I have updated documentation (including README)

### CODE REVIEW

**Review by shubhamparikh927 — APPROVED** [review]

**Comment by semicolin** [comment]
@hankwallace why did those checks fail for "Lint and Test Charts"?

**Comment by semicolin** [comment]
If this is updating our fork from 6.6.0 -> 6.8.0, why does it include upstream commits from 3 years ago (5.6.0)?

**Comment by hankwallace** [comment]
> @hankwallace why did those checks fail for "Lint and Test Charts"?

I hadn't noticed those until you pointed them out. Those are all related to kubernetes deployment test. They appear to be related to blob verification. There is even a pull request submitted against the component repo to add an option to disable this functionality.

https://github.com/helm/chart-testing-action/pull/131

Since we don't deploy with kubernetes, I'd like to move forward without having to resolve these.

**Comment by hankwallace** [comment]
> If this is updating our fork from 6.6.0 -> 6.8.0, why does it include upstream commits from 3 years ago (5.6.0)?

Thats a good question. I assume that the method I used to merge commits was different that the one that @shubhamparikh927 had used in the past.

**Pull request merged**
