### PR TITLE
Mitigate log4j vulnerablity

### PR DESCRIPTION
**Pull request by shubhamparikh927**
Mitigated log4j vulnerablity.
1. Before mitigation
Screenshot from 2021-12-15 17-57-22
2. After mitigation
Screenshot from 2021-12-15 17-57-40

### CODE REVIEW

**Review by ddjain — APPROVED** [review]

**Comment by hankwallace** [comment]
Instead of this, I'd rather see an update of our fork from the upstream repo. Does the upstream repo have a fix for this?

**Comment by shubhamparikh927** [comment]
@hankwallace I scanned the 2nd latest release from the upstream repo `helm-v0.6.0`. This also contains log4j-api vulnerability. Working on local to merging over code with the upstream repo.

**Comment by hankwallace** [comment]
> @hankwallace I scanned the 2nd latest release from the upstream repo `helm-v0.6.0`. This also contains log4j-api vulnerability. Working on local to merging over code with the upstream repo.

let's get the upstream changes merged and then resolve the vulnerability.

**Comment by shubhamparikh927** [comment]
Closing this PR as discussed in the above comments

**Pull request closed without merging**
